# Numpy:
### 1. NumPy (Numerical Python) is a Python library used for fast mathematical and scientific calculations.
### 2. It provides powerful tools for working with arrays, matrices, and numerical data efficiently.


In [1]:
! pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Python311\python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # single dimension array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape) ##2d array
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
np.arange(0,10,2).reshape(5,1) ## 5 row and 1 col

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))# 3 row and 4 col

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## atrributes in numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("array:\n",arr)
print("shape:",arr.shape) # out (2,3)
print("number of dimenesion:",arr.ndim) # 2
print("size (number of elements:)",arr.size) # 6
print("data type:",arr.dtype) # int 32
print("item size (in bytes):",arr.itemsize) #

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimenesion: 2
size (number of elements:) 6
data type: int64
item size (in bytes): 8


In [18]:
## numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# element wise additon 
print("addition",arr1 + arr2)

# element wise subtration 
print("subtraction",arr1 - arr2)

# element wise additon 
print("multiplication",arr1 * arr2)

# element wise division 
print("addition",arr1 / arr2)

addition [11 22 33 44 55]
subtraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
addition [0.1 0.1 0.1 0.1 0.1]


In [19]:
## Universal Function
arr = np.array([2,3,4,5,6])
## sqrt 
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))
  
# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array : \n",arr)


array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
arr[0][0]
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [32]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [39]:
# modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [43]:
### statistical concept -> Normalization 
# to have a mean os 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalizaed_data = (data - mean) / std_dev
print("Normalization data:", normalizaed_data)


Normalization data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [45]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean 
mean = round(np.mean(data))
print("mean",mean)

# median
median = np.median(data)
print("median",median)

# standard deviation 
std_dev = np.std(data)
print("standard deviation",std_dev)

# variance
variance = np.var(data)
print("variance:",variance)

mean 6
median 5.5
standard deviation 2.8722813232690143
variance: 8.25


In [47]:
## logical operation 

data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]

data[(data>=5) & (data <=8)]

array([5, 6, 7, 8])