## Logistic Regression Implementation

In [173]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [174]:
from sklearn.datasets import make_classification  # create dataset like balanced data and donot need to standardise the  dataset

In [175]:
## create dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [176]:
pd.DataFrame(X).head(5)

,0,1,2,3,4,5,6,7,8,9
0,0.964799,-0.066449,0.986768,-0.358079,0.997266,1.181890,-1.615679,-1.210161,-0.628077,1.227274
1,-0.916511,-0.566395,-1.008614,0.831617,-1.176962,1.820544,1.752375,-0.984534,0.363896,0.209470
2,-0.109484,-0.432774,-0.457649,0.793818,-0.268646,-1.836360,1.239086,-0.246383,-1.058145,-0.297376
3,1.750412,2.023606,1.688159,0.006800,-1.607661,0.184741,-2.619427,-0.357445,-1.473127,-0.190039
4,-0.224726,-0.711303,-0.220778,0.117124,1.536061,0.597538,0.348645,-0.939156,0.175915,0.236224


In [177]:
pd.DataFrame(y).head(5)

,0
0,0
1,1
2,1
3,0
4,1


In [178]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=30,random_state=42)

In [179]:
## Model Training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression() 

In [180]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [181]:
y_pred = logistic.predict(X_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1]


In [182]:
# logistic.predict_proba(X_test)  --> used yo check the prob of point with upper and lower class from bestfit line 

In [183]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [184]:
score = accuracy_score(y_test,y_pred)
print("accuracy score is: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion metrics is :",cm)
print("classification_report is :\n",classification_report( y_test ,y_pred))

accuracy score is:  0.7666666666666667
confusion metrics is : [[11  2]
 [ 5 12]]
classification_report is :
               precision    recall  f1-score   support

           0       0.69      0.85      0.76        13
           1       0.86      0.71      0.77        17

    accuracy                           0.77        30
   macro avg       0.77      0.78      0.77        30
weighted avg       0.78      0.77      0.77        30



In [185]:
## accuracy score is:  0.7666666666666667   (before hyper-parameter tunning and cros-validation)

## Hyper-Parameter tunning and Cross Validation

In [186]:
## for custome parameters or use another parameters we use hyperparamenter tunning(for best attribute selection and doesnot leads to overfitting)
model = LogisticRegression()
penalty=['l1','l2','elasticnet'] # to check best parameters
c_Values = [100,10,1.0,0.01]
solver = ['lbfgs', 'liblinear','newton-cg', 'newton-cholesky', 'sag', 'saga']

In [187]:
## Coverting into key value pair
params = dict(penalty = penalty,C = c_Values,solver=solver)

## Grid-SearchCV

In [188]:
## Grid-SearchCV
from sklearn.model_selection import GridSearchCV , StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [189]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [190]:
grid.fit(X_train,y_train)

c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\91742\AppD

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [191]:
grid.best_params_  ## best combination is selected there 

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [192]:
grid.best_score_

np.float64(0.8680412371134022)

In [193]:
y_pred = grid.predict(X_test)

In [194]:
score = accuracy_score(y_test,y_pred)
print("accuracy score is: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion metrics is :",cm)
print("classification_report is :\n",classification_report( y_test ,y_pred))

accuracy score is:  0.8
confusion metrics is : [[12  1]
 [ 5 12]]
classification_report is :
               precision    recall  f1-score   support

           0       0.71      0.92      0.80        13
           1       0.92      0.71      0.80        17

    accuracy                           0.80        30
   macro avg       0.81      0.81      0.80        30
weighted avg       0.83      0.80      0.80        30



In [195]:
## accuracy score is:  {0.8} after the hyper-parameter tunning and cross validation

## GridSearchCV = “Har possible parameter try karo + cross validation karo + best select karo”

| Parameter  | Meaning                    |
| ---------- | -------------------------- |
| estimator  | Kaunsa model               |
| param_grid | Kaunse parameters try kare |
| scoring    | Accuracy se measure kare   |
| cv         | Cross validation method    |
| n_jobs=-1  | Saare CPU cores use kare   |


## Randomized Search CV

In [196]:
from sklearn.model_selection import RandomizedSearchCV

In [197]:
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator=model,param_distributions=params , cv = 5, scoring='accuracy')

In [198]:
randomcv.fit(X_train,y_train)

c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\91742\AppData

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [199]:
print(randomcv.best_score_)

0.8659793814432991


In [200]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.01}

In [201]:
y_pred = randomcv.predict(X_test)

In [202]:
score = accuracy_score(y_test,y_pred)
print("accuracy score is: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion metrics is :",cm)
print("classification_report is :\n",classification_report( y_test ,y_pred))

accuracy score is:  0.8
confusion metrics is : [[12  1]
 [ 5 12]]
classification_report is :
               precision    recall  f1-score   support

           0       0.71      0.92      0.80        13
           1       0.92      0.71      0.80        17

    accuracy                           0.80        30
   macro avg       0.81      0.81      0.80        30
weighted avg       0.83      0.80      0.80        30



In [203]:
# why we use randomcv becuz when we have large number of parameters it take less number of time compare to GridSearchCV

## Logistic Regression for Multiclass classification Problem

In [204]:
## create dataset
X,y = make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [205]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]], shape=(1000, 10))

In [206]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [207]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=30,random_state=42)

In [209]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

c:\Users\91742\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [210]:
y_pred

array([2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       2, 0, 1, 0, 2, 0, 0, 2])

In [211]:
score = accuracy_score(y_pred,y_test)
print("accuracy score is: ",score)
cm = confusion_matrix(y_pred,y_test)
print("confusion metrics is :",cm)
print("classification_report is :\n",classification_report(y_pred,y_test))

accuracy score is:  0.6
confusion metrics is : [[7 5 0]
 [1 2 1]
 [1 4 9]]
classification_report is :
               precision    recall  f1-score   support

           0       0.78      0.58      0.67        12
           1       0.18      0.50      0.27         4
           2       0.90      0.64      0.75        14

    accuracy                           0.60        30
   macro avg       0.62      0.58      0.56        30
weighted avg       0.76      0.60      0.65        30

